### ISSUE TITLE
DataFrame formats undone by itable

### ISSUE THREAD

**Issue by fja05680** [mgymrek/itable#6]
Hi, First I've been looking for several days for a way to highlight DataFrame elements.  Glad I found this.  The issue, any "formatting" that I applied to a DataFrame is undone with itable.  For example, if I round DataFrame values to 2 decimals, this gets undone after itable.  Additionally, dates go from this ''2015-01-04 ' to this '2015-01-04T19:00:00.000000000-0500'.  After looking at the code, I realized that itable.PrettyTable is not a DataFrame, and the index and row/column values get copied from the DataFrame and converted to strings.  It would be nice to be able to specify some formats for these.  For my current use case, date format and number rounding.  I may give this a go myself.

update 2015-04-28:  It appears that I should be able to do this by specifying a "format_function".

update 2015-04-29: Specifying the "format_function" within set_cell_style() allowed me to format the column data, i.e. pt.set_cell_style(cols=[col], format_function=lambda x: format(x, '.2f')).  However, this didn't work for index data using update_row_header_style().  It appears to ignore the "format_function" argument.  As a workaround, I converted the index to a column, i.e. df.reset_index(level=0, inplace=True).

update 2015-04-28: I just performed a pull-request that fixes this issue.

thanks!
Farrell

**Comment by mgymrek** [comment]
Excellent, thanks for the PR!
