### ISSUE TITLE
Working with pandas.DataFrame.transpose doesn't work

### ISSUE THREAD

**Issue by marcomayer** [mgymrek/itable#8]
Just tried our your module and really like it. But I work a lot with transposing tables, so for example I might have 

df = pd.DataFrame({"x":[1,2,3], "y":[6,4,3], "z":["testing","pretty","tables"], "f":[0.023432, 0.234321,0.5555]})

but then need to transpose it to:

df = df.T

which will cause a type error using prettytable:

itable.PrettyTable(df)

TypeError: Can't convert 'numpy.int64' object to str implicitly.

Right now my solution is to convert the columns to string on my own before using PrettyTable but I thought it might be a nice feature to have this done automatically since a lot of people transpose DFs.

Thanks for your work!

Marco

**Comment by mgymrek** [comment]
I just tried this  example with the latest version and had no problems. Please reopen if you're still having problems.
