### ISSUE TITLE
Using .iteritems() on a dict doesn't work in python 3.x

### ISSUE THREAD

**Issue by marcomayer** [mgymrek/itable#9]
Multiple times in itable.py

        for key, value in kwargs.iteritems():

is used. This doesn't work in python 3.x

Replacing it with 

        for key, value in kwargs.items():

solves the issue.

**Comment by mgymrek** [comment]
Fixed in [this commit](https://github.com/mgymrek/itable/commit/18874b9ab4fb6724accb7a8729d3e62b20f1ae91).

**Comment by cdqncn** [comment]
good

**Comment by lsxinh2** [comment]
use .items() instead?

**Comment by MarceloCorreiaData** [comment]
The correct is 
for key, value in dict.items():
    if value == 1234:
        print(key)
